tap "homebrew/bundle"
tap "homebrew/cask-fonts"

brew "argocd"
brew "devspace"
brew "direnv"
brew "git"
brew "helix"
brew "helm"
brew "httpie"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "midnight-commander"
brew "openssl"
brew "pass"
brew "pdm"
brew "pre-commit"
brew "pyenv"
brew "python@3.12"
brew "readline"
brew "sqlite"
brew "starship"
brew "tmux"
brew "zsh-autosuggestions"
brew "uv"

cask "firefox"
cask "font-fira-code"
cask "iterm2"
cask "lens"
cask "maccy"
cask "obsidian"
cask "raycast"
cask "rectangle"
cask "sourcetree"
cask "telegram"
cask "visual-studio-code"
cask "zed"

mas "Amphetamine", id: 937984704
mas "Monosnap", id: 540348655
mas "The Unarchiver", id: 425424353
mas "Nautik for Kubernetes", id: 1672838783
