tap "FelixKratz/formulae"

brew "argocd"
brew "devspace"
brew "direnv"
brew "gh"
brew "git"
brew "gitleaks"
brew "go-task/tap/go-task"
brew "grpcurl"
brew "helix"
brew "helm"
brew "httpie"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "midnight-commander"
brew "openssl"
brew "pass"
brew "pre-commit"
brew "pyenv"
brew "python@3.12"
brew "python@3.13"
brew "readline"
brew "rustup"
brew "sketchybar"
brew "sqlite"
brew "starship"
brew "tmux"
brew "tox"
brew "uv"
brew "zsh-autosuggestions"

cask "blender"
cask "firefox"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "ghostty"
cask "iterm2"
cask "lens"
cask "maccy"
cask "nikitabobko/tap/aerospace"
cask "obsidian"
cask "raycast"
cask "rectangle"
cask "sourcetree"
cask "telegram"
cask "visual-studio-code"
cask "zed"

mas "Amphetamine", id: 937984704
mas "Mattermost", id: 1614666244
mas "The Unarchiver", id: 425424353
